name: position_tools
channels:
- conda-forge
- defaults
- menpo
dependencies:
- "python>=3.6"
- numpy
- scipy
- matplotlib
- tqdm
- bottleneck
- opencv
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
