{% set name = "position_tools" %}
{% set version = "0.1.0.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5d86cc1095237fc58d5ab8d46cbcf60bd379b263be8e82f9f8f4238c4e074e09

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.11
    - opencv
    - pip
    - python
    - scipy
    - tqdm
  run:
    - numpy >=1.11
    - opencv
    - python
    - scipy
    - tqdm

test:
  imports:
    - position_tools
  requires:
    - pytest >=2.7.1

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file:
  summary: ""
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
